<!--
Created by Nicolas Torquet at 20/12/2023
torquetn@igbmc.fr
Copyright: CNRS - INSERM - UNISTRA - ICS - IGBMC
CNRS - Mouse Clinical Institute
PHENOMIN, CNRS UMR7104, INSERM U964, Université de Strasbourg
Code under GPL v3.0 licence
-->

<template>
 <v-main>
    <v-container>
      <h1><v-icon icon="mdi-cloud-upload"></v-icon> Repositories</h1>
      <v-card>
        <v-alert-title>To change</v-alert-title>
        <v-card-text>
          We would like to conform to the FAIR (Findable, Accessible, Interoperable, Reusable) principles. According to them,
          several organizations have created repositories to promote Open Data. For instance,
          Zenodo and Dataverse can be used to store data for free and to generate for each of them a DOI (Digital Object Identifier)
          for each of them. DOI are increasingly requested by the publishers to render data available.<br />
          <br />
          If the available data are linked to FAIR repositories, mouseTube will become also FAIR and finally everyone will benefit of this.<br />
          <br />
          On mouseTube, we noticed a number of broken links for shared files. Therefore,
          we strongly recommend to put your files on a scientific repository such as the ones cited above.
          We encourage you to create an account on one of these repositories and store data there instead of on your own server.
          We added a DOI field in the mouseTube database, so that the DOI can be entered in addition of the link.
          For files that are already linked in mouseTube, please check whether the link is still working. If not, please use the link and
          DOI generated by a repository to update the data.
          If you host your files on Zenodo, you can select the mouseTube community (communities section) when you enter your file information.<br />
          Thank you for taking this information into consideration.
        </v-card-text>
      </v-card>


      <v-skeleton-loader v-if="dataLoaded==false">
      </v-skeleton-loader>

      <v-card v-else variant="outlined" class="mt-5" v-for="repository in repositories">
        <v-card-title><img :src="repository.logo" /> - {{ repository.name_repository }}</v-card-title>
        <v-card-text>
            {{ repository.description }}
        </v-card-text>
      </v-card>
    </v-container>
 </v-main>
</template>


<script>
import axios from "axios";
export default {
  name: "repositories",
  data: function(){
		return {
      repositories: [],
      dataLoaded: false
    }
  },
  methods: {
    getRepositories() {
      axios.get(`http://127.0.0.1:8000/api/repository`)
          .then(response => {
            this.repositories = response.data
            console.log(this.repositories)
            this.dataLoaded = true
          })
          .catch(error => {
            console.log(JSON.stringify(error))
          })
    },
  },
  mounted() {
    this.getRepositories()
  }
}
</script>


<style scoped>

</style>