<!--
Created by Nicolas Torquet at 20/12/2023
torquetn@igbmc.fr
Copyright: CNRS - INSERM - UNISTRA - ICS - IGBMC
CNRS - Mouse Clinical Institute
PHENOMIN, CNRS UMR7104, INSERM U964, Université de Strasbourg
Code under GPL v3.0 licence
-->

<script setup>
////////////////////////////////
// IMPORT
////////////////////////////////

import { ref, onMounted } from 'vue';
import axios from 'axios';

////////////////////////////////
// DATA
////////////////////////////////

const loading = ref(true);
const repositories = ref([]);
const areas = ref([]);
const areaSelect = ref('');
const search = ref('');

////////////////////////////////
// METHODS
////////////////////////////////

const getRepositories = async () => {
  try {
    const response = await axios.get(`http://127.0.0.1:8000/api/repository`);
    repositories.value = response.data;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify(error));
  }
};

const getAreas = async () => {
  try {
    const response = await axios.get(`http://127.0.0.1:8000/api/country`);
    for (const [key, value] of Object.entries(response.data)) {
      areas.value.push({ key, value });
    }
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify(error));
  }
};

////////////////////////////////
// ON MOUNTED
////////////////////////////////

// Fetch repositories and areas when the component is mounted
onMounted(async () => {
  await getRepositories();
  await getAreas();
  loading.value = false;
});
</script>

<template>
  <v-main>
    <v-container>
      <h1><v-icon icon="mdi-cloud-upload"></v-icon> Repositories</h1>
      <v-card class="mt-5" color="grey-lighten-4">
        <v-alert-title class="mt-2 ml-2"
          ><v-icon icon="mdi-information-variant-circle" class="mr-2"></v-icon> To
          change</v-alert-title
        >
        <v-card-text>
          <nuxt-link href="https://www.go-fair.org/fair-principles/" target="_blank"
            ><v-img :width="300" class="mt-3 mb-3" src="fair_data_principles.jpg" alt="FAIR"></v-img
          ></nuxt-link>
          We would like to conform to the FAIR (Findable, Accessible, Interoperable, Reusable)
          principles. According to them, several organizations have created repositories to promote
          Open Data. For instance, Zenodo and Dataverse can be used to store data for free and to
          generate for each of them a DOI (Digital Object Identifier) for each of them. DOI are
          increasingly requested by the publishers to render data available.<br />
          <br />
          If the available data are linked to FAIR repositories, mouseTube will become also FAIR and
          finally everyone will benefit of this.<br />
          <br />
          On mouseTube, we noticed a number of broken links for shared files. Therefore, we strongly
          recommend to put your files on a scientific repository such as the ones cited above. We
          encourage you to create an account on one of these repositories and store data there
          instead of on your own server. We added a DOI field in the mouseTube database, so that the
          DOI can be entered in addition of the link. For files that are already linked in
          mouseTube, please check whether the link is still working. If not, please use the link and
          DOI generated by a repository to update the data. If you host your files on Zenodo, you
          can select the mouseTube community (communities section) when you enter your file
          information.<br />
          Thank you for taking this information into consideration.
        </v-card-text>
      </v-card>

      <v-skeleton-loader class="mt-5" type="table-heading, list-item-two-line" v-if="loading">
      </v-skeleton-loader>

      <v-skeleton-loader class="mt-5" type="table-heading, list-item-two-line" v-if="loading">
      </v-skeleton-loader>

      <v-data-iterator
        v-else
        class="mt-5"
        :items="repositories"
        :items-per-page="15"
        :search="search"
      >
        <template v-slot:header>
          <v-toolbar class="px-2">
            <v-text-field
              v-model="search"
              clearable
              density="comfortable"
              hide-details
              placeholder="Search"
              prepend-inner-icon="mdi-magnify"
              style="max-width: 300px"
              variant="solo"
            ></v-text-field>
          </v-toolbar>
        </template>

        <template v-slot:default="{ items }">
          <v-container class="pa-2" fluid>
            <v-card class="mt-5" v-bind="repository" v-for="repository in items">
              <v-card-title
                ><img :src="repository.raw.logo" :alt="repository.raw.name_repository"
              /></v-card-title>
              <v-card-subtitle
                ><strong>{{ repository.raw.name_repository }}</strong> -
                {{ repository.raw.area }}</v-card-subtitle
              >
              <v-card-item>
                {{ repository.raw.description }}
              </v-card-item>
              <v-divider class="mx-4 mb-1"></v-divider>
              <v-card-actions>
                <v-btn variant="text" color="teal-accent-4">
                  <v-icon icon="mdi-link-variant"></v-icon>
                  <a :href="repository.raw.url" target="_blank"> Website</a>
                </v-btn>
                <v-btn variant="text" color="teal-accent-4">
                  <v-icon icon="mdi-api"></v-icon>
                  <a :href="repository.raw.url_api" target="_blank">{{ repository.raw.url_api }}</a>
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-container>
        </template>
      </v-data-iterator>
    </v-container>
  </v-main>
</template>

<style scoped>
a {
  text-decoration: none;
  color: teal;
}

a:hover {
  text-decoration: underline;
}
</style>
