<!--
Created by Nicolas Torquet at 20/12/2023
torquetn@igbmc.fr
Copyright: CNRS - INSERM - UNISTRA - ICS - IGBMC
CNRS - Mouse Clinical Institute
PHENOMIN, CNRS UMR7104, INSERM U964, Université de Strasbourg
Code under GPL v3.0 licence
-->

<script setup>
////////////////////////////////
// IMPORT
////////////////////////////////

import { ref, onMounted } from 'vue';
import axios from 'axios';
import { Warehouse } from 'lucide-vue-next';

////////////////////////////////
// DATA
////////////////////////////////

const loading = ref(true);
const repositories = ref([]);
const areas = ref([]);
const areaSelect = ref('');
const search = ref('');
const apiBaseUrl = useApiBaseUrl();

const baseUrl = computed(() => apiBaseUrl.replace(/\/api\/?$/, ''));

////////////////////////////////
// METHODS
////////////////////////////////

const getRepositories = async () => {
  try {
    const response = await axios.get(`http://127.0.0.1:8000/api/repository`);
    repositories.value = response.data;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify(error));
  }
};

const getAreas = async () => {
  try {
    const response = await axios.get(`http://127.0.0.1:8000/api/country`);
    for (const [key, value] of Object.entries(response.data)) {
      areas.value.push({ key, value });
    }
  } catch (error) {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify(error));
  }
};

////////////////////////////////
// ON MOUNTED
////////////////////////////////

// Fetch repositories and areas when the component is mounted
onMounted(async () => {
  await getRepositories();
  await getAreas();
  loading.value = false;
});
</script>

<template>
  <v-main>
    <v-container>
      <v-row>
        <v-col>
          <v-card variant="flat" class="mx-auto" max-width="1000">
            <div class="d-flex align-center mt-1 mb-4">
              <h1><Warehouse /> Repositories</h1>
              <v-chip v-if="repositories.length > 0" class="me-1 my-1 mx-2">
                {{ repositories.length }}
              </v-chip>
            </div>
            <v-card class="mt-5" color="grey-lighten-4">
              <v-card-text>
                We would like to conform to
                <nuxt-link href="https://www.go-fair.org/fair-principles/" target="_blank">
                  the FAIR (Findable, Accessible, Interoperable, Reusable) principles.
                </nuxt-link>
                According to them, several organizations have created repositories to promote Open
                Data. For instance, Zenodo and Dataverse can be used to store data for free and to
                generate for each of them a DOI (Digital Object Identifier) for each of them. DOI
                are increasingly requested by the publishers to render data available.<br />
                <br />
                If the available data are linked to FAIR repositories, mouseTube will become also
                FAIR and finally everyone will benefit of this.<br />
                <br />
                On mouseTube, we noticed a number of broken links for shared files. Therefore, we
                strongly recommend to put your files on a scientific repository such as the ones
                cited above. We encourage you to create an account on one of these repositories and
                store data there instead of on your own server. We added a DOI field in the
                mouseTube database, so that the DOI can be entered in addition of the link. For
                files that are already linked in mouseTube, please check whether the link is still
                working. If not, please use the link and DOI generated by a repository to update the
                data. If you host your files on Zenodo, you can select the mouseTube community
                (communities section) when you enter your file information.<br />
                Thank you for taking this information into consideration.
              </v-card-text>
            </v-card>

            <v-skeleton-loader class="mt-5" type="table-heading, list-item-two-line" v-if="loading">
            </v-skeleton-loader>

            <v-skeleton-loader class="mt-5" type="table-heading, list-item-two-line" v-if="loading">
            </v-skeleton-loader>

            <v-data-iterator
              v-else
              class="mt-5"
              :items="repositories"
              :items-per-page="15"
              :search="search"
            >
              <template v-slot:header>
                <v-toolbar rounded="lg" class="px-2 border-sm">
                  <v-text-field
                    v-model="search"
                    clearable
                    density="comfortable"
                    hide-details
                    placeholder="Search"
                    prepend-inner-icon="mdi-magnify"
                    style="max-width: 300px"
                    variant="solo"
                  ></v-text-field>
                </v-toolbar>
              </template>

              <template v-slot:default="{ items }">
                <v-container class="pa-2" fluid>
                  <v-card
                    class="mt-5 border-sm"
                    v-bind="repository"
                    v-for="repository in items"
                    :key="repository.raw.name"
                    elevated
                  >
                    <div
                      v-if="repository.raw.logo"
                      style="
                        position: absolute;
                        top: 12px;
                        right: 16px;
                        width: 56px;
                        height: 56px;
                        background: #fff;
                        border: 1px solid #eee;
                        border-radius: 10px;
                        overflow: hidden;
                        z-index: 2;
                        display: flex;
                        align-items: center;
                        justify-content: center;
                      "
                    >
                      <img
                        :src="baseUrl + repository.raw.logo"
                        :alt="repository.raw.name"
                        style="
                          width: 100%;
                          height: 100%;
                          object-fit: contain;
                          transform: scale(1.3);
                        "
                      />
                    </div>
                    <v-card-title>{{ repository.raw.name }}</v-card-title>
                    <v-card-subtitle>{{ repository.raw.area }}</v-card-subtitle>
                    <v-card-item>
                      {{ repository.raw.description }}
                    </v-card-item>
                    <v-divider class="mx-4 mb-1"></v-divider>
                    <v-card-actions>
                      <v-btn variant="text" color="rgba(198, 40, 40, 0.9)">
                        <v-icon icon="mdi-link-variant"></v-icon>
                        <a :href="repository.raw.url" target="_blank"> Website</a>
                      </v-btn>
                      <v-btn variant="text" color="rgba(198, 40, 40, 0.9)">
                        <v-icon icon="mdi-api"></v-icon>
                        <a :href="repository.raw.url_api" target="_blank">{{
                          repository.raw.url_api
                        }}</a>
                      </v-btn>
                    </v-card-actions>
                  </v-card>
                </v-container>
              </template>
            </v-data-iterator>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </v-main>
</template>

<style scoped>
a {
  text-decoration: none;
  color: rgba(198, 40, 40, 0.9);
}

a:hover {
  text-decoration: underline;
}
</style>
